### ISSUE TITLE
How to build 2-level clusterization, based on attributes

### ISSUE THREAD

**Issue by ayerix** [Leaflet/Leaflet.markercluster#1015] opened 2020-11-06 15:38 UTC
How can we archive a functionality like so:
- on the lower level of zoom (like zoom 12 or closer) we have no clusterization at all
- on the middle zoom (probably like 8 to 12) we have a clusterization by a single attribute (let say "region" clusterization)
- on the higher zoom (less then 8) we have a clusterization by another parent attribute (like "country")
No level of clusterization depends on distance between the markers and they are switched by zoom changing

Is this possible? I tried manually create a region markers partition by "region" markerClusterGroup()-s and then copy their's generated clusters to "country" MarkerClusterGroup into it's __gridClusters[zoom from 8 to 12], but seems not go, no luck (
I'm asking for help.. please

**Comment by IvanSanchez** [comment] 2020-11-06 17:38
Duplicate of #1010, #476. Filter your data and create a `MarkerClusterGroup` instance per category. Leverage `maxZoom`/`minZoom`.

**Closed by IvanSanchez** 2020-11-06 17:38 UTC

**Comment by ayerix** [comment] 2020-11-07 07:26
No! You don't read my message carefully! I know how to group them by category on the first level! I can't re-group them (make a union of union) on the higher level! That's the difference. So I need first level clusterization based on a pair of attributes (region + country) and 2nd level clusterization (on a higher zoom) based on a single attribute value (country only)

**Comment by ayerix** [comment] 2020-11-07 07:27
> Duplicate of #1010, #476. Filter your data and create a `MarkerClusterGroup` instance per category. Leverage `maxZoom`/`minZoom`.

No! You don't read my message carefully! I know how to group them by category on the first level! I can't re-group them (make a union of union) on the higher level! That's the difference. So I need first level clusterization based on a pair of attributes (region + country) and 2nd level clusterization (on a higher zoom) based on a single attribute value (country only)
Please reopen the issue, it's not a duplicate

**Comment by IvanSanchez** [comment] 2020-11-07 15:04
> I can't re-group them on the higher level!

Yes you can group them on a higher level.

**Comment by ayerix** [comment] 2020-11-07 16:38
Nop, there is no way to do that.
Here is what I done:
`const markers1 = [marker([55.179, 61.373]), marker([55.173, 61.371]), marker([55.172, 61.379]), marker([55.178, 61.372]), marker([55.171, 61.372]), marker([55.182, 61.373]), marker([55.171, 61.376])];
    const markers2 = [marker([55.181, 61.371]), marker([55.183, 61.375]), marker([55.182, 61.377]), marker([55.181, 61.371]), marker([55.174, 61.376]), marker([55.179, 61.378]), marker([55.175, 61.378])];
    const group1 = markerClusterGroup();
    const group2 = markerClusterGroup();
    group1.addLayers(markers1);
    group2.addLayers(markers2);
    group1.addTo(this.map);
    group2.addTo(this.map);`
and what I see is:
close view: [https://prnt.sc/vf7jq7](pict) yes they are grouped as we want to, by groups
far view: [https://prnt.sc/vf7kd2](pict) far away they will not be grouped on any zoom-out level
another one test, same markers, but:
`const group1 = markerClusterGroup();
    const group2 = markerClusterGroup();
    group1.addLayers(markers1);
    group2.addLayers(markers2);
    const group3 = markerClusterGroup();
    group3.addLayers([group1, group2]);
    group3.addTo(this.map);`
This time we have a correct joining on zoom-out [https://prnt.sc/vf7lod](pict)
But we lose groups on close view [https://prnt.sc/vf7ma6](pict)

We can't combine both approaches together at the same time. Either we have a partition, or we have a normal clusterization

The only solution I actually found is to override _generateInitialClusters function of MarkerClusterGroup to fill _gridClusters and _gridUnclustered with my custom (also overriden) DistanceGrid-s that can pay respect not only to distances between the points, but also to my attributes on particular zoom level. This works, but this is not a good-looking solution

**Comment by IvanSanchez** [comment] 2020-11-07 18:05
> We can't combine both approaches together at the same time. Either we have partitionA, or we have partitionB, we can't switch them somewhere in the middle of scaling

Yes you can. `map.on('zoomend', function(){ if (map.getZoom() > 10) { group3.remove(); group1.addTo(map); group2.addTo(map) }  else { group3.addTo(map); group1.remove(); group2.remove() } });`

**Comment by ayerix** [comment] 2020-11-07 18:25
> > We can't combine both approaches together at the same time. Either we have partitionA, or we have partitionB, we can't switch them somewhere in the middle of scaling
> 
> Yes you can. `map.on('zoomend', function(){ if (map.getZoom() > 10) { group3.remove(); group1.addTo(map); group2.addTo(map) } else { group3.addTo(map); group1.remove(); group2.remove() } });`

Yes, this is possible sollution (this was a first solution I tried), but it has one disadvantage: as far as I understand it breaks the smooth animation on zoom from level 10 and back. That is because of layers have completely different child-parent dependents and animation tree, so we have smooth transition on any scale except 10. 
It probably may be fixed with a very small, but appreciated feature, a kind of filtering function, passed to the MarkerClusterGroup among the options, which fitlers considered markers depending on zoom level (it can be used in _generateInitialClusters to skip the points we would like not to participate in clustering). I think that is a small, but very desirable feature sometimes.
