### ISSUE TITLE
2-level clusterization, based on attributes

### ISSUE THREAD

**Issue by ayerix** [Leaflet/Leaflet.markercluster#1016] opened 2020-11-06 15:38 UTC
How can we achieve a functionality like so:
- on the lower level of zoom (like zoom 12 or closer) we have no clusterization at all
- on the middle zoom (probably like 8 to 12) we have a clusterization by a single attribute (let say "region" clusterization)
- on the higher zoom (less then 8) we have a clusterization by another parent attribute (like "country")
No level of clusterization depends on distance between the markers and they are switched by zoom changing

I understand that I can make an attribute-based partition of markers and clusterize them separately by a single attribute (by adding different MarkerClusterGroup for each group of markers). it solves the problem with grouping items by region. but there is no way to join them together on country-level, on max zoomout, because they stay unmixable on higher levels of zoom. Also I can make two different clusterization by region and by country and switch them on zoom changing, but it breaks animation for particular zoom level which switches clusterization type, so it's not really cool. 

Is this possible? I tried manually create a region markers partition by "region" markerClusterGroup()-s and then copy their's generated clusters to "country" MarkerClusterGroup into it's __gridClusters[zoom from 8 to 12], but seems not go, no luck (
I'm asking for help.. please

**Comment by IvanSanchez** [comment] 2020-11-06 17:38
Duplicate of #1015.

**Closed by IvanSanchez** 2020-11-06 17:38 UTC
