### ISSUE TITLE
With Markercluster spiderfied, setView does not work properly

### ISSUE THREAD

**Issue by deristnochda** [Leaflet/Leaflet.markercluster#712] opened 2016-08-30 17:14 UTC
I use a map with several clustered markers and a list with links opening the popups for the corresponding marker. This is done without zoomToShowLayer, but instead keeps the current zoom level and spiderfies the visual parent of a marker. A minimal example can be found below. In order to see the issue, please click "Open Popup 1" first and then "Open Popup 4"

http://jsbin.com/xofudolule/1/edit?html,js,output

Apparently, the setView does not work properly. However, without the line `vp.spiderfy()` the map centers correctly. Am I doing something wrong?

The issue does not appear, if both clusters are visible on the map. Also, if the zoom level is high enough such that no markers are clustered, everything works as expected.

Browser: Chrome Version 52.0.2743.116 m on Windows 7 and Safari 9.1.2 on OS X 10.11
Leaflet 1.0.0-rc.1
markercluster 1.0.0-rc.1

**Comment by danzel** [comment] 2016-08-30 21:40
I think spiderfy internally sets the view? check the code.

**Comment by deristnochda** [comment] 2016-08-31 09:11
I have found no calls of setView or panTo corresponding to spiderfying. Also, a little test in the above example without the lines

`mymap.setView(pos, mymap.getZoom());`
`m.openPopup();`

show no movement of the map (of course, the spiderfy only works, when both clusters are visible).

However, openPopup seems to be setting the view and if I drop that line, the map is centered correctly and the spiderfying works as expected, see the jsbin below

http://jsbin.com/xofudolule/2/edit?html,js,output

As far as I understand the issue now, this has to do with one cluster still being spiderfied. But I have no clue why this does not happen when both clusters (the spiderfied one and the one to be spiderfied) are both visible.

A workaround is in the jsbin below, where the cluster is first unspiderfied. I do not know, if this is the correct way to do that, but at least it works for me.

http://jsbin.com/toyudileci/1/edit?html,js,output

**Comment by danzel** [comment] 2017-01-26 21:43
Ok, I accidentally ran in to this bug and sorta fixed it.
The problem is if you have a spiderfied marker with a popup shown, then close the spider.
When this happens we move the marker, which means the popup gets moved, which means the map scrolls to keep it in the view.

I've made markercluster explicitly close the popup before closing the spiderfy. If this doesn't fix it in your case, try close the popup yourself. Pretty certain the internal fix will handle it however.

**Closed by danzel** 2017-01-26 21:43 UTC
