### ISSUE TITLE
draggable markers (aka as issue#57)

### ISSUE THREAD

**Issue by niconil** [Leaflet/Leaflet.markercluster#426] opened 2014-12-01 11:20 UTC
i read the description of issue #57

i try to follow the given instructions
each time a marker is dragged on my map i remove it and then add it again in the layer

i wrote a jsfiddle to show my issue 
http://jsfiddle.net/niconil/1wLLfuja/5/

i have a set of 3 markers with the same coordinates
i can select one marker and drag it outside the cluster : it works

but if i drag the same marker again it disappear from the map

do i make something wrong or is it a bug ?

**Comment by danzel** [comment] 2015-12-21 22:42
Dupe of #335

**Closed by danzel** 2015-12-21 22:42 UTC
