### ISSUE TITLE
Indicate if clustering/unclustering in animationend-event

### ISSUE THREAD

**Issue by andyentity** [Leaflet/Leaflet.markercluster#619] opened 2016-01-07 17:02 UTC
I need to perform different actions when markers are clustered/unclustered. However it seems that the `animationend`-event does not provide any information indicating the animation direction with it.

Are there any other approaches suggested or has this use case never occured before? If not, I'd like to propose that either an event-object will be passed to the callback or that two sub-event-types are being introduced - `clusterend` and `unclusterend` - that are getting fired together with `animationend` respectively.

**Comment by fallaciousreasoning** [comment] 2016-01-08 03:19
I agree, this would be quite useful. It might be worth adding a list of the markers that were clustered or unclustered as part of the object.

**Comment by danzel** [comment] 2016-01-10 20:45
We could maybe add some detail to this event. Or you could just track the zoom level changes?

**Comment by danzel** [comment] 2017-01-26 00:23
Happy to have this added if it is useful.
I haven't seen any other requests for it though and I'm not sure what your use case is, so closing.

**Closed by danzel** 2017-01-26 00:23 UTC

**Comment by Azmisov** [comment] 2018-02-01 22:36
I would like to open/close a popup when the a marker is clustered / unclustered. The popup is not attached to the marker directly... it is just associated with it. I have cached a value `popup_marker` and need to detect whether this marker has just been clustered / unclustered to toggle a popup.

I found out I could detect the unclustering always calls the `iconCreateFunction` (correct me if I'm wrong). So I added the open popup trigger to that. But I still need a way to detect when the marker gets clustered again. Any suggestions?

**Comment by mirko77** [comment] 2019-03-18 15:41
I have a similar issue. 

I open a sidebar when a marker is clicked, and I close it when the popup is dismissed.

The problem is when the user changes the zoom level: the popup gets dismissed if the marker gets into a cluster but my sidebar is still visible as I could not find a way to listen for the "clustering" event and close the sidebar when it happens

**Comment by mirko77** [comment] 2019-03-18 15:43
> I would like to open/close a popup when the a marker is clustered / unclustered. The popup is not attached to the marker directly... it is just associated with it. I have cached a value `popup_marker` and need to detect whether this marker has just been clustered / unclustered to toggle a popup.
> 
> I found out the unclustering always calls the `iconCreateFunction` (correct me if I'm wrong). So I added the open popup trigger to that. But I still need a way to detect when the marker gets clustered again. Any suggestions?

@Azmisov have you found a solution to this: "_But I still need a way to detect when the marker gets clustered again._" ??

**Comment by Azmisov** [comment] 2019-03-18 18:02
Yes, I believe I did. You can do something like this:

    iconCreateFunction: function(c){
        if (!c.is_spiderfied){
            for (const n of c.getAllChildMarkers()){
                markerClustered(n);
                // or you can do something more specific like this:
                if (n == active_popup_marker)
                    closeActivePopup();
            }
        }
    }

There is no event I know to detect a marker being clustered directly. However, the `iconCreateFunction` gets called when it creates the meta "clustered" icon; the children of the meta icon are all the markers that were clustered.

The `c.is_spiderfied` flag I set manually based on the `spiderfied` and `unspiderfied` events. If you aren't using the spiderfy feature, you can remove that part.
