### ISSUE TITLE
Clusters are not displayed at negative zoom levels

### ISSUE THREAD

**Issue by david4096** [Leaflet/Leaflet.markercluster#752] opened 2017-01-25 07:04 UTC
## How to reproduce

- Leaflet version I'm using: 1.0.0
- Leaflet.MarkerCluster version I'm using: npm 1.0.1
- Browser (with version) I'm using: chromium  55.0.2883.87
- OS/Platform (with version) I'm using: ubuntu gnome 16.10
- step 1

Set the minzoom on the map to be a negative number.

- step 2

Add clusters and zoom to a negative zoom level.

## What behaviour I'm expecting and which behaviour I'm seeing

Should still be able to cluster at negative zoom levels.

**Comment by IvanSanchez** [comment] 2017-01-25 08:30
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by danzel** [comment] 2017-01-25 19:19
Dupe of #704 (I've just renamed it now).
Shouldn't be too hard to fix, I was hoping one of the users in that thread might take a look.

**Closed by danzel** 2017-01-25 19:19 UTC

**Comment by david4096** [comment] 2017-01-25 20:00
Thanks @danzel !!!
