### ISSUE TITLE
Doesn't support negative zoom levels (Cluster icons don't show up/disappears)

### ISSUE THREAD

**Issue by vovan2016** [Leaflet/Leaflet.markercluster#704] opened 2016-08-09 20:33 UTC
Hi,

I am using an imageOverlay map for my indoor floorplan project with bounds set to the image exact resolution. In the example below it is 2003px*1203px, but it can be higher. 
I encountered following issues:
1. The cluster icon doesn't show up when the map is loaded.
2. The cluster icon and the non-clustered marker icon can disappear and show up after zooming (mostly on low zoom levels).
3. The icon's positioning on the map is not correct at some zoom levels (mostly low zoom).
4. After "playing" with zoom for some time a second cluster icon can appear so you can see 2 clusters for the same markers. Though this happens very rarely and i couldn't reproduce this issue intentionally.

If i change the bounds from 
    `var bounds = [[0,0], [1203, 2003]]`
to smaller values like
    `var bounds = [[0,0], [120.3, 200.3]]`
all seem to be working correctly.
But i would like to keep the big bounds for my project...

Please take a look at the example: [https://jsfiddle.net/8voh7rLs/](https://jsfiddle.net/8voh7rLs/)
For this example i used Leaflet 1.0.0-beta.2 and Markercluster 1.0.0-rc.1.0

Thanks!

**Comment by danzel** [comment] 2016-08-09 21:49
At a glance, I don't think we support negative minZoom

**Comment by vovan2016** [comment] 2016-08-09 23:30
The negative minZoom seems to be the root cause indeed. 
Thank you for pointing on it! 
Looks like I will have to rewrite all my code accordingly :(
Please let me know if you can think of any solution to keep the negative zoom + big bounds.

**Comment by trisys3** [comment] 2016-11-14 17:08
We are using a similar layout, because we show floor plans, as well. We set a `minZoom` directly, using a complicated function to figure out what it is, but same idea. We may not need clustering, as it does not look as nice with 1000's of markers, but we are looking into it. We may still use spiderification, if users put markers really close together or even on top of each other.

Just putting myself out there as another voice in need of markerCluster *and* `minZoom` at the same time.

**Comment by BruceHubbard** [comment] 2016-12-07 13:25
@danzel I'm also having an issue with negative zoom (I have large images I'm using as a map).  There are a couple of instances where the min zoom is hard coded to 0 like this:

```
		for (var zoom = maxZoom; zoom >= 0; zoom--) {
			this._gridClusters[zoom] = new L.DistanceGrid(radiusFn(zoom));
			this._gridUnclustered[zoom] = new L.DistanceGrid(radiusFn(zoom));
		}
```

would it be as simple as using map.getMinZoom() instead of 0?  Where else would the code need to change?

**Comment by danzel** [comment] 2016-12-07 19:31
That'd probably do it.
I'm not sure where, look for other place we compare zooms.
I'll need a test case for this too, check the `spec/` folder

**Comment by david4096** [comment] 2017-01-25 20:00
Thanks @danzel +1 I experienced this.

**Comment by danzel** [comment] 2017-01-25 20:01
I'm planning to take a look at this shortly

**Comment by danzel** [comment] 2017-01-25 20:48
This should be fixed now.
Please try the latest git, or grab a built version from below and report back
https://gist.github.com/danzel/986636912dd3cde1e4f3c6ecf6908c7e

If this works then I'll do a new build.

**Comment by david4096** [comment] 2017-01-25 21:27
Thanks, I just tested this and I was able to get markers past the 0 zoom level. The problem I observed is that the existing cluster titles disappeared when moving from 0 to -1. Remaining markers drawn at the negative zoom level seem to behave properly.

**Comment by danzel** [comment] 2017-01-25 21:32
Could you show me how to reproduce this?

**Comment by david4096** [comment] 2017-01-25 23:30
This is what I'm coding against, it's not a very brief example but will demonstrate the behavior at the commit https://github.com/david4096/datlas/commit/8e2a61f0ab4c57474e0583e328ec1b6ec6a247df .

**Comment by danzel** [comment] 2017-01-26 00:15
Ah thanks, have reproduced. Working on it...

**Comment by danzel** [comment] 2017-01-26 00:21
Ok, pushed up a fix.
Please give it a go, copy of the built version is here:
https://gist.github.com/danzel/fbfe3e535169376599948ada797b2422

**Comment by danzel** [comment] 2017-01-26 21:38
Closing as I'm pretty certain this works correctly now.

**Closed by danzel** 2017-01-26 21:38 UTC

**Comment by trisys3** [comment] 2017-01-31 02:59
It seems to work. Thanks.
