### ISSUE TITLE
(4a095f) Parent is null when adding layer causing null reference error

### ISSUE THREAD

**Issue by CramerTV** [Leaflet/Leaflet.markercluster#337] opened 2014-03-28 21:10 UTC
I'm receiving a null reference error when adding a marker to the map.  Is there anything I could be doing outside the plugin to create this issue?  I'm only using the API (addLayer, removeLayer, etc.)

/// line ~757
_addLayer: function (layer, zoom)

/// line ~789
var parent = closest.__parent;
if (parent) {
	this._removeLayer(closest, false);
}
/// line ~804 is where I'm getting the error since parent is null
for (z = zoom - 1; z > parent._zoom; z--) { 
	lastParent = new L.MarkerCluster(this, z, lastParent);
	gridClusters[z].addObject(lastParent, this._map.project(closest.getLatLng(), z));
}
parent._addChild(lastParent);

**Comment by danzel** [comment] 2015-12-21 22:35
Dupe of #335 or should be fixed by marker move support in master

**Closed by danzel** 2015-12-21 22:35 UTC
