### ISSUE TITLE
Create a cluster based on a polygon

### ISSUE THREAD

**Issue by ptrsz** [Leaflet/Leaflet.markercluster#629] opened 2016-01-20 07:41 UTC
Hi,
Is it possible somehow to make the ClusterGroups based on geoJSON polygons? I want to specify to boundaries of each clustergroup, based on geographical geometries, not (only) zoom level.

**Comment by IvanSanchez** [comment] 2016-01-20 10:26
Duplicate of #521

**Closed by IvanSanchez** 2016-01-20 10:26 UTC
