### ISSUE TITLE
How to form cluster by country or any specific attribute.

### ISSUE THREAD

**Issue by krishnaisdinesh** [Leaflet/Leaflet.markercluster#749] opened 2017-01-17 06:16 UTC
I want to create cluster by country or any specific attribute of markergroup object. Currenlty its forming on the basic of some radius.

**Comment by IvanSanchez** [comment] 2017-01-17 08:29
Create several instances of `L.MarkerClusterGroup`, one per country (or unique attribute value).

Duplicate of #694, #521, #493, #390.

**Closed by IvanSanchez** 2017-01-17 08:29 UTC
