### ISSUE TITLE
Leaflet anchor changes on declustering

### ISSUE THREAD

**Issue by Klapsa2503** [Leaflet/Leaflet.markercluster#707] opened 2016-08-25 14:35 UTC
I have an issue with custom icons. I create my markers using custom icon (setting anchor and iconSize) and everything looks at the beggining

![good](https://cloud.githubusercontent.com/assets/6784771/17973069/475ade00-6ae1-11e6-8bc5-1e2f57150621.png)

But when i do following things:
1. Open a map with clustered icons
2. Zoom out so that markers will cluster
3. Zoom in so that marker will uncluster
     and now markers are not pointing where they should.

![bad2](https://cloud.githubusercontent.com/assets/6784771/17973063/43732860-6ae1-11e6-8d05-ca9a17df5215.png)

as you see the marker and it's label looks weird and what is important is that label is in correct spot (icon is moved)

This issue is on both 0.7 and 1.0 so I would recommend to fix this on 0.7

**Comment by ghybs** [comment] 2016-08-26 05:06
Hi,

Please could you share your code and reproduce your issue on an online editing tool, like [Leaflet playground](http://playground-leaflet.rhcloud.com/), Plunker, or JSFiddle?

With the only information you provided above, please understand that it is almost impossible to tell what is the reason for the behaviour you describe.

If you already have some ideas on what should be fixed, please provide some details and code.

**Comment by Klapsa2503** [comment] 2016-08-26 07:42
I am displaying map in JavaFX WebVIew and I have noticed that the issue appeared when I upgraded my Java version from 1.8.0_65 to 1.8.0_112

This is my code that I use (some of the functions are called from Java):

`<html>
<head>
    <link rel="stylesheet" href="css/leaflet.css"/>
    <link rel="stylesheet" href="css/leaflet.label.css"/>
    <link rel="stylesheet" href="css/MarkerCluster.Default.css"/>
    <link rel="stylesheet" href="css/MarkerCluster.css"/>

    <style>
        body {
            padding: 0;
            margin: 0;
        }

        html, body, #map {
            height: 100%;
            width: 100%;
        }
    </style>

    <script src="js/jquery-1.11.3.min.js"></script>
    <script src="js/leaflet.js"></script>
    <script src="js/leaflet.label-src.js"></script>
    <script src="js/leaflet.markercluster.js"></script>
</head>
<body>

<div id="map"></div>

<script>

    var app; //Reference to Java controller class

    var markerClusterGroupOptions = {
        showCoverageOnHover: false,
        maxClusterRadius: 45,
        spiderfyDistanceMultiplier: 2,
        removeOutsideVisibleBounds: false,
        animateAddingMarkers: false
    };

    //The following variables are accessed from Java code
    var units;
    var events;
    var map = L.map('map', {
        zoomControl: false
    });

    var controlLayers = L.control.layers();
    controlLayers.addTo(map);

    map.attributionControl.addAttribution('&copy; autorzy OpenStreetMap');
    map.attributionControl.setPrefix(false);


    //Clear and remove layers (prevents memory leaks)
    function removeLayer(map, layer) {
        if (layer !== undefined) {
            controlLayers.removeLayer(layer);
            layer.clearLayers();
            map.removeLayer(layer);
        }
    }

    //Calling Javascript functions from Java
    function changeLayers(clustered) {
        removeLayer(map, units);
        removeLayer(map, events);

        //Set new type of layer
        if (clustered) {
            units = new L.markerClusterGroup(markerClusterGroupOptions);
            events = new L.markerClusterGroup(markerClusterGroupOptions);
        } else {
            units = new L.LayerGroup();
            events = new L.LayerGroup();
        }
        map.addLayer(units);
        map.addLayer(events);
        controlLayers.addOverlay(units, "Zasoby mobilne");
        controlLayers.addOverlay(events, "Zdarzenia");
    }
    function initializeApp(newApp, clustering) {
        app = newApp;
        changeLayers(clustering);
    }
    function createMarker(lat, lon, icon, label, draggable) {
        var latlng = L.latLng(lat, lon);
        var marker = L.marker(latlng, {icon: icon, draggable: draggable, keyboard: false});
        return marker.bindLabel(label);
    }
    function createIcon(iconUrl, iconAnchor, iconSize) {
        if (iconSize) {
            return L.icon({iconUrl: iconUrl, iconSize: iconSize, iconAnchor: iconAnchor});
        }
        return L.icon({iconUrl: iconUrl, iconAnchor: iconAnchor});
    }

    //Scale shown on map (metric and imperial)
    L.control.scale().addTo(map);
</script>

</body>
</html>
`

**Comment by danzel** [comment] 2016-08-28 21:41
JavaFX WebView is not supported.
If this reproduces on leaflet playground (as linked above) in a modern browser, then we may be able to look at it.
Otherwise, closing.

**Closed by danzel** 2016-08-28 21:41 UTC
