### ISSUE TITLE
Uncaught TypeError: Cannot read property 'trim' of undefined cdn 1.0.0

### ISSUE THREAD

**Issue by GitMorin** [Leaflet/Leaflet.markercluster#724] opened 2016-10-03 14:17 UTC
Hi!

I get the error message on 
var clusterLayer = new L.MarkerClusterGroup

I use the leaflet 1.0.1 and I also tried using the cdn
https://unpkg.com/leaflet@1.0.0-rc.3/dist/leaflet.js

But the problem still seem to appear.
Any idea what to issue could be or how i could be resolved?

**Comment by IvanSanchez** [comment] 2016-10-03 14:24
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by GitMorin** [comment] 2016-10-03 16:15
Here is a fiddle
https://jsfiddle.net/w7pjgLns/1/
However i got a different error this time 
Uncaught TypeError: L.markerClusterGroup is not a function

First time doing a fiddle I hope i got it right.

**Comment by ryanjhodge** [comment] 2016-10-06 01:40
I'm also getting this error after updating a project to Leaflet 1.0.1/Leaflet.markercluster 1.0.0.  The project contains a custom `MarkerClusterGroup` layer which I added to a JSFiddle. The example below displays the error.

http://jsfiddle.net/ryanjhodge/pozg2s9u/

@GitMorin @IvanSanchez

**Comment by IvanSanchez** [comment] 2016-10-06 07:47
That is being caused by this line in **your** code:

```
    this._featureGroup.on(L.FeatureGroup.EVENTS, this._propagateEvent, this);
```

`L.FeatureGroup.EVENTS` is `undefined` in Leaflet 1.0.x. Which happens because you folks are blindly [copy-pasting code from the 0.7.x branch of MarkerCluster](https://github.com/Leaflet/Leaflet.markercluster/blob/leaflet-0.7/src/MarkerClusterGroup.js#L54) into your code (without using proper delegation of parent constructor calls to `L.MarkerClusterGroup.prototype.initialize.call()`), and expecting it to work seamlessly.

Error happens in user code, not markercluster code, nor leaflet code → closing.

**Closed by IvanSanchez** 2016-10-06 07:47 UTC

**Comment by jtank38** [comment] 2018-09-21 14:53
With all due respect can you please elaborate the solution? I didn't get your brief answer? I am using django  1.9 which has leafflet version 1.3.x. So is this a version error or do I have to change something in my code? I simply followed the readme.md provided in repo.
