### ISSUE TITLE
Spiderifying with a lot of markers breaks page rendering

### ISSUE THREAD

**Issue by francislavoie** [Leaflet/Leaflet.markercluster#868] opened 2018-01-29 18:29 UTC
- [x] I'm reporting a bug, not asking for help
- [x] I'm sure this is a Leaflet.MarkerCluster code issue, not an issue with my own code nor with the framework I'm using (Cordova, Ionic, Angular, React…)
- [x] I've searched through the issues to make sure it's not yet reported

----

## How to reproduce

- Leaflet version I'm using: 1.3.1
- Leaflet.MarkerCluster version I'm using: 1.3.0
- Browser (with version) I'm using: Chrome
- OS/Platform (with version) I'm using: Linux
- Clusters at max zoom with ~200+ items
- Spiderify is gliching out the entire page, entire blocks of the page fail to render, crazy stuff. Hard to track down why, I don't see anything unusual in the DOM. See the weird grey sections to the right and bottom right, and half the table below is cut off O_O

![example](https://user-images.githubusercontent.com/2111701/35527266-2c88e038-04f8-11e8-88e8-8d9ad48f506d.png)

- Zooming back out (which cancels spidering) fixes it and the page renders properly again.

## What behaviour I'm expecting and which behaviour I'm seeing
Shouldn't mangle the page!

I'd be happy with an option that could let me make a workaround, i.e. `spiderfyOnMaxZoom` allowing a closure that can return true/false based on some conditions, for example size of the cluster (I could do `return clusterSize < 100;` and just not spiderify on really big clusters)

## Minimal example reproducing the issue

I'll have to set up a jsfiddle at some point later, a bit tight on time right now but I should be able to do it later.

Options I'm using: 
```js
    var cluster = L.markerClusterGroup({
        maxClusterRadius: 35,
        spiderLegPolylineOptions: { weight: 1, color: '#222', opacity: 0.2 },
        chunkedLoading: true,
    });
```

**Comment by danzel** [comment] 2018-01-29 20:17
LMK when there is a jsfiddle up, looks like maybe we are upsetting the browser, but we could be doing something wrong.

**Comment by francislavoie** [comment] 2018-01-30 20:41
@danzel Gave a shot at making a fiddle: https://jsfiddle.net/e2ap85fd/1/

Click on the cluster, then move your mouse around, you should see parts of the page randomly disappear and just general lagginess and missing markers.

**Comment by danzel** [comment] 2018-01-31 02:31
I can't reproduce in chrome on windows here, Chrome 64. 64-bit.

To double check, you mean move the mouse over the "Run, Update, Fork" icons at the top of the jsfiddle page right?

**Comment by francislavoie** [comment] 2018-01-31 03:27
Yep.

Huh, odd. Just tried it myself on Chrome 64 windows (home machine), and I can't seem to replicate. I could've sworn I've seen it happen there. I'll try to collect more info, but it might just be localized to linux.

**Comment by ghybs** [comment] 2018-01-31 17:09
Hi,

Cannot replicate either with the provided JSFiddle on Chromium 63 Ubuntu 16.04 (64b)

**Comment by francislavoie** [comment] 2018-01-31 17:15
I'm using ElementaryOS 0.4.1, which is based on Ubuntu 16.04 (has a different window manager though). Weird. :cry:

**Comment by francislavoie** [comment] 2018-02-12 16:12
I guess I might close this. It's probably an upstream issue with Chrome/Linux. Not sure what to do about it.

@danzel how do you feel about this suggestion I gave above?

>I'd be happy with an option that could let me make a workaround, i.e. spiderfyOnMaxZoom allowing a closure that can return true/false based on some conditions, for example size of the cluster (I could do `return clusterSize < 100;` and just not spiderify on really big clusters)

**Comment by danzel** [comment] 2018-02-12 23:53
If you check out the code behind spiderfyOnMaxZoom, you can implement the functionality in your app instead by listening to `clusterclick` events.
Closing

**Closed by danzel** 2018-02-12 23:53 UTC

**Comment by francislavoie** [comment] 2018-02-13 00:02
Ah okay @danzel, I see that I can do `c.layer._childCount` (where c is the cluster event), but how do I cancel spidering? `return false;` doesn't cancel that from happening.
