### ISSUE TITLE
Clicking in center of marker on a line closes the cluster

### ISSUE THREAD

**Issue by savannahjune** [Leaflet/Leaflet.markercluster#559] opened 2015-09-28 17:05 UTC
Lines are draw on top of marker icons, so if a user clicks on an icon in the center of it, the cluster will close as the click event is happening on the line, not in the icon.

**Comment by danzel** [comment] 2015-09-29 20:10
Lines should be below markers, and have always been historically afaik.
Can you reproduce this?

**Comment by savannahjune** [comment] 2015-10-13 17:15
Sure, here's a gif showing that if you click in the middle of the circle marker you can click the line on top and collapse the cluster.  

Let me know if that's clear enough (unfortunately github won't allow me to upload a video directly).

![leafletmarkercluster](https://cloud.githubusercontent.com/assets/2073292/10462369/34f2c806-7193-11e5-815f-9de6cfa23352.gif)

**Comment by danzel** [comment] 2015-10-13 19:32
Can you reproduce this in a jsfiddle or similar?

**Comment by ghybs** [comment] 2015-10-14 08:27
Hi,

It looks like these are `L.CircleMarker`'s.

I guess they would be drawn on the `overlayPane` (http://leafletjs.com/reference.html#map-overlaypane), the same as the spiderfying legs.

Since the latter are created just after having added the markers to the map (in [animated](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L179) and [non-animated](https://github.com/Leaflet/Leaflet.markercluster/blob/master/src/MarkerCluster.Spiderfier.js#L137) versions), they appear on top.

Demo: http://jsfiddle.net/zn7q7or6/7/

To overcome this specific behaviour with `L.CircleMarker`'s, we could reverse the order of addition to the map, or push the spiderfying legs at bottom using `L.Path.bringToBack()` after they are added to the map.

Uncomment line 65 in the above demo and re-run to test the latter proposition.

**Comment by savannahjune** [comment] 2015-10-15 00:11
Thanks @ghybs using L.Path.bringToBack() fixed my issue!

**Comment by danzel** [comment] 2015-12-22 00:26
This doesn't appear to happen in the 1.0 version, expect this was fixed in #585

**Closed by danzel** 2015-12-22 00:26 UTC
